Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -27,7 +27,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
       - timeout-minutes: 1
         run: |
-          function verify() {
+          function check() {
             printf 'binary: %s == ' "$1" >&2
             curl --location https://github.com/iterative/cml/releases/latest/download/cml-linux-x64 --output cml && chmod a+x cml && ./cml --version |
               tee /dev/stderr | fgrep -- "$1" || return 1
@@ -38,14 +38,13 @@ jobs:
             npx @dvcorg/cml --version |
               tee /dev/stderr | fgrep -- "$1" || return 1
           }
-          while ! verify $(npm version --json | jq --raw-output '.["@dvcorg/cml"]'); do
+          while ! check $(npm version --json | jq --raw-output '.["@dvcorg/cml"]'); do
             timeout --preserve-status 64 sleep $((2**++exponent)) # exponential backoff
           done
       - if: failure()
-        run: >
-          curl "$SLACK_WEBHOOK"
-          --header 'Content-type: application/json'
-          --data '{"text": "Release of <https://github.com/iterative/cml|cml> failed!"}'
+        run: |
+          echo "Release of <https://github.com/iterative/cml|cml> failed!" | jq --raw-input {text:.} |
+          curl --header content-type:application/json --data @- "$SLACK_WEBHOOK"
         env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
   release:
